### ISSUE TITLE
Support 'symlog' scale

### ISSUE THREAD

**Issue by wass88** [d3/d3-scale#105]
Matplotlib supports 'symlog' scale.
https://matplotlib.org/examples/scales/scales.html

Symlog is defined as the following expression.
```
(-1 < x < 1) ? x :
(x >= 1) ? log(x) :
  -log(-x)
```
This scale is useful for extensive domains.

Is it possible to support symlog in d3-scale? Otherwise, is there a workaround to use custom scales?

**Comment by mbostock** [comment]
Seems like a reasonable suggestion.

**Comment by danielnaab** [comment]
@mbostock If I were to look into this - is there a preferred implementation direction? One could add an option to the log scale, or create a separate symlog module.

If a separate module, I'm curious if there is a good pattern to follow to extend the log scale without duplicating code.

Any suggestions would be greatly appreciated!

**Comment by slavikdenis** [comment]
Looks great so far :) Would be really great if it would work with generating axis and rescaling while zoom and pan! Keep up the good work @danielnaab

**Comment by mattpitkin** [comment]
It would be great to see the symlog scale (in part so it can be included in Vega vega/vega#1392, Vega-Lite vega/vega-lite#4127, and Altair altair-viz/altair#1077) and it looks like @danielnaab has done nice work on it. Is there likely to be movement on merging #134 soon?

**Comment by jkreft-usgs** [comment]
@danielnaab just added documentation as requested by @curran

**Comment by Tillsten** [comment]
I am a regular user of symlog scales in matplotlib I think this PR is missing that the linear threshold and the scale factor of the scale is changeable. The former limits the linear domain and the latters determines the relative scaling of the log and the linear parts.

**Comment by mbostock** [comment]
I have an implementation in #156 slated for release in d3-scale 2.2.0. I ended up using a slightly different formulation of symlog, though, as recommended in [“A bi-symmetric log transformation for wide-range data” by Webber, 2012](https://www.researchgate.net/publication/233967063_A_bi-symmetric_log_transformation_for_wide-range_data).
