### ISSUE TITLE
Excluding d3-time and d3-timeFormat in npm install

### ISSUE THREAD

**Issue by greenafrican** [d3/d3-scale#106]
> (You can omit d3-time and d3-time-format if you’re not using d3.scaleTime or d3.scaleUtc.)

What is the best way to exclude these when using npm? I looked into `--no-optional` but these aren't optional dependencies for d3-scale.

**Comment by mbostock** [comment]
I’m not sure if that’s easily doable. That parenthetical comment applies primarily to a vanilla JavaScript environment. If you’re using a bundler like Rollup that does tree-shaking, then you should automatically benefit from dead code removal, meaning that if you don’t use d3.scaleTime or d3.scaleUtc, it shouldn’t pull in d3-time or d3-time-format. (However, note that Rollup’s detection of side-effect free code is conservative, see rollup/rollup#305 rollup/rollup#1293; you may have to adjust your imports to give Rollup hints as to what code you actually want to use.)

We could mark these as optionalDependencies in the package.json, but I don’t think that’s what we want; there’s no equivalent to putting a try-catch block around `require` when the code is written as ES6 static imports.
