### ISSUE TITLE
Minor issue in scaleQuantize implementation

### ISSUE THREAD

**Issue by aimeos** [d3/d3-scale#109]
`scaleQuantize()` returns the highest value in the range instead of the lowest. This makes a difference if the domain ranges from 0 to 0 because there are no values yet. In this example, it would always return "steelblue":
```
d3.scaleQuantize()
    .domain([0, 0])
    .range(["brown", "steelblue"]);
```
Expected would be the lowest value in this case ("brown").

**Comment by mbostock** [comment]
The current behavior seems correct to me, although this is a degenerate case so I’m not sure whether either behavior is more reasonable or if the choice is arbitrary.

The scale rounds up at the threshold, similar to how Math.round(0.5) returns 1. So:

```js
var scale = d3.scaleQuantize()
    .domain([0, 1])
    .range(["brown", "steelblue"]);

scale(0.5); // "steelblue"
```

And similarly:

```js
var scale = d3.scaleQuantize()
    .domain([0, 0])
    .range(["brown", "steelblue"]);

scale(0); // "steelblue"
```
