### ISSUE TITLE
Support distance scaling in scaleLinear?

### ISSUE THREAD

**Issue by w1ndy** [d3/d3-scale#114]
To scale the distance between a and b with scaleLinear:
```js
scaleLinear(b) - scaleLinear(a)
```
This requires a and b to be known in advance. Is there a convenient way to do this? Something like:
```js
scaleLinear.scaleDistance(b - a)
```

**Comment by curran** [comment]
This is doable with the existing API.

How about this:

scaleLinear(b-a) - scaleLinear(0)

**Comment by w1ndy** [comment]
Sure it'll do, but still I think it would be handy to integrate such function into linear scale.

For example if we would like to know what does 1 unit of domain correspond to,
```js
scaleLinear.distance(1)
```
would be much more interpretable than
```js
scaleLinear(1) - scaleLinear(0)
```

**Comment by curran** [comment]
This might be a good place to write a small function inside your code, to make it more interpretable, like this:

```js
scaleLinear.distance = value => scaleLinear(value) - scaleLinear(0);
```

Then your code could look like this:

```js
scaleLinear.distance(1);
```

As this logic is so small, and doesn't generalize to all scale types (e.g. log, sqrt, time), I'm not sure it makes sense to add it to the library. Although, if you do still think it would be a good addition, feel free to make a pull request and see where it could fit in the code.

**Comment by w1ndy** [comment]
@curran OK, I'll implement this and use it in my own code. Thanks for your answers! Closing the issue now.
