### ISSUE TITLE
How to position x-axis ticks at the middle of bars

### ISSUE THREAD

**Issue by aimeos** [d3/d3-scale#120]
For a bar chart we would like the ticks of the x-axis to be in the middle of the bars, not at the beginning like shown here:
![image](https://user-images.githubusercontent.com/8647429/31308320-3568bd36-ab75-11e7-8deb-e639f7c12070.png)
How can we achieve this?

**Comment by mbostock** [comment]
You should use a band scale, d3.scaleBand. (Alternatively, you can position your bands manually starting at half-integer values rather than integers.)
