### ISSUE TITLE
Time scale ignores 24 formating

### ISSUE THREAD

**Issue by amaino** [d3/d3-scale#124]
I am trying to use the time scale for a graph that can contains data that span from several months to just a day. I would therefore like to use the dynamic formating of the time scale but it does not work as it is hardcoded to use 12 h formating wich looks very strange in swedish as we never use that.

I looked in the [code ](https://github.com/d3/d3-scale/blob/4c8c282d5f0ac938b4841ce6851389e7f0f545ba/src/time.js#L33) and saw that this is hardcoded and did not see a simple way to remove this limitation. I would say that 24h format is way more important so should be hardcoded instead, but understand that this may not be agreed on by all.

So can this be fixed or is there a workaround to make it work without the need of a custom d3 installed.

**Comment by mbostock** [comment]
Per the README, you should roll your own multi-scale time format and pass that to scale.tickFormat.

https://github.com/d3/d3-time-format/blob/master/README.md
