### ISSUE TITLE
d3.scaleTime() and deep zooming

### ISSUE THREAD

**Issue by Algooo** [d3/d3-scale#125]
See following code:
http://jsbin.com/tuwikekuya/1/edit?js,output

When you zoom in too deep inside the view. Moving of the view on x-axis does not work properly any more.
The ticks are jumping instead of moving smooth like they do for y-axis.
The problem occurs when using d3.scaleTime(). For d3.scaleLinear() eveything is good.

**Comment by mbostock** [comment]
This is the expected behavior. The problem is that Date objects in JavaScript only have millisecond resolution, so you will need to limit the ability to zoom in or switch to a linear scale if you want sub-millisecond precision.
