### ISSUE TITLE
An even nicer() nice()

### ISSUE THREAD

**Issue by kollerp** [d3/d3-scale#128]
It would be great to have some sort of nice() that avoids axis overlap in charts :
![screenshot--2017-12-02-22-06-22-265](https://user-images.githubusercontent.com/34196638/33519723-25b91ebc-d7ad-11e7-94bb-5bd668362747.png)

I realize that there are solutions where you manipulate the domain to add "padding", but it would be really great if there was a way to add this padding in a generic way.

**Comment by ITsvetkoFF** [comment]
Looks like an idea that worth discussion. I think a lot of devs are solving this problem in the way that suits specific use-case. For instance you can have some wrapper on top of axis and domain and handle those paddings there. And I am not sure that it can be done elegantly enough inside scale and axis as proposed here.

**Comment by mbostock** [comment]
Folding into #150.
