### ISSUE TITLE
sequentialScale with same lower and upper bound produces incorrect value

### ISSUE THREAD

**Issue by GrubbyHalo** [d3/d3-scale#130]
If i have sequential scale with the same values for the domain and i call/apply it with the same input value as the domain values, i get an a color value that is not within the range of the color interpolater i specified.
e.g.

```js
var ss=d3.scaleSequential(d3.interpolateBlues);
ss.domain([1000,1000]);
ss(1000); // "rgb(0, 0, 0)"
```

any other value produces the correct result.
Is this expected behavior ?

**Comment by mbostock** [comment]
I think this should be considered a bug; the scale should probably return *interpolate*(0) for all inputs if the domain is collapsed. (Though if the domain contained NaN, I think *interpolate*(NaN) would be appropriate, which is what is happening here, erroneously.)
