### ISSUE TITLE
Minimum import to use d3-scale

### ISSUE THREAD

**Issue by nuthinking** [d3/d3-scale#131]
What is the minimum import to use d3-scale with colors?

for example to use:

`d3.scaleLinear().domain([0,1]).range(['#9277CC','#7FBBEA']);`

I tried initially to import only `https://d3js.org/d3-scale.v1.min.js` and then adding d3-color and d3-interpolation but I still get odd errors (usually involving cubehelix).

In case the code pen is [here](https://codepen.io/nuthinking/pen/RxJaoQ?editors=1111).

Thanks a lot!

**Comment by mbostock** [comment]
Please see the README where this topic is coveredZ

**Comment by nuthinking** [comment]
Looks like for what I need neither Collection and Format are needed. Array made the trick. Thanks again!
