### ISSUE TITLE
d3 .ticks outputting wrong range

### ISSUE THREAD

**Issue by VanessaChu** [d3/d3-scale#135]
My code is as follows
```

const xScale = scaleTime()
  .domain([new Date(reports[reports.length - 1].date), new Date(reports[0].date)])
  .range([margin.left, width]
```
where the domain is the date 2018-02-25 to 2018-03-03

I want my x axis to show the 7 days: Sun 25, Mon 26, Tues 27, Wed 28, Thu 1, Fri 2, Sat 3

So i use d3's .ticks to get these tickvalues

`const ticksX = xScale.ticks(timeDay, 1)`
However what I get is 6 days: Sun 25, Mon 26, Tues 27, Wed 28, Thu 1, Fri 2

So I tried to increment my right domain by 1 with momentjs:

`moment(new Date(reports[0].date)).add(1, 'days')`
INSTEAD I get 8 days: Sun 25, Mon 26, Tues 27, Wed 28, Thu 1, Fri 2, Sat 3, Mon 4

What is going on here? I can't find the pattern.

**Comment by mbostock** [comment]
I’m not able to reproduce this issue:

https://beta.observablehq.com/@mbostock/d3-scaletime-ticks-test

If you’d like me to investigate, please give me enough information to reproduce this issue, preferably by forking the notebook above. At a minimum, I need to know the exact value of the domain (if it’s not `[new Date(2018, 1, 25), new Date(2018, 2, 3)]`), which timezone you are in, which browser you are using, and which version of d3-scale you are using. Thank you.
