### ISSUE TITLE
rename dist folder to build to be more in line with other d3- packages

### ISSUE THREAD

**Issue by leon** [d3/d3-scale#136]
Hi!

A lot of the other d3- packages have their build folder named build, but d3-scale is named dist.

I'm still stuck in concat land, and I was lost a while before I realized the folder wasn't named the same as the others. :)

**Comment by mbostock** [comment]
I am renaming them to dist as this is the more common convention. Eventually they should all use dist but I won’t be changing them synchronously.

The path of the generated file isn’t considered part of the public API; instead, you should use the package.json to determine the names of the files.
