### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by shaunlebron** [d3/d3-scale#138]
[BigInts](https://github.com/tc39/proposal-bigint) are coming to Chrome soon.  Trying something like this in Chrome Canary, using a BigInt domain `[0n, 10n]`:

```js
d3.scaleLinear().domain([0n,10n]).range([0,10])
```
<img width="455" alt="screen shot 2018-04-20 at 2 41 32 pm" src="https://user-images.githubusercontent.com/116838/39070429-02f809f6-44a9-11e8-9177-a342618b3e17.png">

**Comment by mbostock** [comment]
Maybe, but I’m doubtful. From the [proposal](https://github.com/tc39/proposal-bigint):

> A key design decision is to disallow mixed operations between BigInts and Numbers.

So, in keeping with the intent of the BigInt API, I think it’d be the caller’s responsibility to convert from BigInt to Number outside of the scale API.

**Comment by shaunlebron** [comment]
I think I agree.  Even if d3-scale was made to work with BigInts for both the domain and range, it would still break when trying to rescale it with d3-zoom, since the transforms are floats. 

```js
const a = d3.scaleLinear().domain([0n,10n]).range([12345n,23456n]); // could be made to work?
const b = d3.event.transform.rescaleX(a); // probably can't work
```

My use case is to zoom through a graph of unusually large/precise numbers. I'm just not sure how to do this properly yet without rebuilding d3-scale, d3-zoom, and d3-interpolate to use [bignumber.js](https://github.com/MikeMcl/bignumber.js/).  I'll keep thinking on this.

**Comment by shaunlebron** [comment]
To clarify, my goal is to actually create a high-precision scale by taking advantage of the new BigInts:

```js
d3.scaleLinear().domain([2n**56n, 2n**64n]).range(...)
```

For this to work, the number coercion might have to look like this:

```js
function number(x) {
 if (typeof x === 'bigint') return x;
 return +x;
}
```

and d3-interpolate would have to work with the new bigint types as well.
