### ISSUE TITLE
Port mpl colormaps?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-scale#14]
https://bids.github.io/colormap/

[![b75883984a032ea0ba26](https://cloud.githubusercontent.com/assets/230541/10670737/cd446d12-789b-11e5-8a66-585ba8fab8f0.png)](http://bl.ocks.org/mbostock/b75883984a032ea0ba26)

The only “problem” is they are defined discretely, rather than continuously. So they might need to be quantize scales?

**Comment by timelyportfolio** [comment]
Perhaps this will be helpful https://github.com/politiken-journalism/scale-color-perceptual.

**Comment by mbostock** [comment]
Those appear to just use the list of discrete colors, which are already available from the OP. But that’s the basic idea, yeah.

**Comment by sjmgarnier** [comment]
@mbostock Not D3, but we ported the matplotlib colormaps to R (https://github.com/sjmgarnier/viridis), and used splines to reconstruct continuous scales from the discrete values provided by the matplotlib team. Not sure if it can be done with D3, but this was a cheap and easy (and a bit dirty) solution in R at least.

**Comment by mbostock** [comment]
@sjmgarnier Thanks for the link. Are your splines in RGB colorspace? I was worried that implementing the splines would involve implementing [CIECAM02](https://en.wikipedia.org/wiki/CIECAM02), which I believe is how they were initially designed. (I’m aware of two existing implementations, [baskerville/ciecam02](https://github.com/baskerville/ciecam02) and [jrus/chromatist](https://github.com/jrus/chromatist), so maybe it’d be worthwhile, anyway.)

I [tested quantize scales](http://bl.ocks.org/mbostock/b75883984a032ea0ba26), and it seems to work fine. (Though, I subsequently removed them from that example because it wasn’t necessary to render the colormap.)

**Comment by sjmgarnier** [comment]
@mbostock Yes, they are in RGB space. I'm not sure it's the most sensible way to implement this, but it was the easiest one given all the tools available in base R.
