### ISSUE TITLE
d3.scaleBand handle null and 'null'

### ISSUE THREAD

**Issue by ThomasChan** [d3/d3-scale#140]
Hi:

https://github.com/d3/d3-scale/blob/916f68e71cdc42d1c70e94843c294b07e007c04e/src/ordinal.js#L26

Assume our `domain` is `[null, '', 'null']`, in this line of code `_[i] + ''` will transform `null` to `'null'`, thus we only got result `['null', '']` not `[null, '', 'null']`.

I suppose this is a normal case, `domain` maybe contains `null` when user using their csv or database table data to draw a `bar` chart.

**Comment by mbostock** [comment]
This is the expected, documented behavior, and I don’t plan on special-casing null or undefined. Per the README:

> Thus, an ordinal scale’s values must be coercible to a string, and the stringified version of the domain value uniquely identifies the corresponding range value.
