### ISSUE TITLE
What happened to sideEffects: false

### ISSUE THREAD

**Issue by marcofugaro** [d3/d3-scale#145]
Sorry, this is not related to d3-scale but to d3 in general.

What happened to adding `"sideEffects": false` to `d3`'s package.json?

This would allow us to do `import { scaleLinear } from 'd3'` without having to require the entire library if using webpack4.

There was once an issue to d3 main repo, but the issues there have been removed.

Is this possible? Will we in the future be able to do `import { scaleLinear } from 'd3'` and only have in the bundle the `scaleLinear` function?

**Comment by mbostock** [comment]
I closed the D3 issues due to spam and people not following the issue guidelines.

The support for Webpack’s sideEffects flag stalled because I do not know which D3 modules are considered “pure” and therefore do not know whether enabling this flag will break users.

**Comment by marcofugaro** [comment]
so the true `import { scaleLinear } from 'd3'` is currently impossible?
