### ISSUE TITLE
Linear scale shorthand returns passed value

### ISSUE THREAD

**Issue by dnlfrst** [d3/d3-scale#160]
# Issue
I'd expect a linear scale with given domain and range to return the same value (i. e. `x(20) === y(20)` should hold) regardless of the shorthand being used or not. However, that's not the case:
```javascript
var x = d3
  .scaleLinear()
  .domain([10, 130])
  .range([0, 960]);
var y = d3.scaleLinear([10, 130], [0, 960]);

console.log(x(20), y(20)); // 80, 20
```
An MWE can be found [here](https://jsfiddle.net/624quwba/).

# Question
Is this a bug or am I using the shorthand incorrectly?

**Comment by mbostock** [comment]
You are using d3-scale 2.1. The shorthand will be available in d3-scale 2.2, which has not been released yet. Please find the documentation for d3-scale 2.1 here:

https://github.com/d3/d3-scale/blob/v2.1.2/README.md
