### ISSUE TITLE
Allow customizing top paddingOuter separate from bottom paddingOuter

### ISSUE THREAD

**Issue by melissachang** [d3/d3-scale#164]
I am trying to implement this mock:

![1](https://user-images.githubusercontent.com/10929390/54061630-8a339380-41b6-11e9-8c8e-70bd5b4d2d88.png)

I can't because `paddingOuter` applies to top and bottom. For this mock, top `paddingOuter` should be 0px and bottom `paddingOuter` should be 7px.

If I set `paddingOuter` to 7px:

![2](https://user-images.githubusercontent.com/10929390/54061738-09c16280-41b7-11e9-83ef-47036508f30d.png)

If I set `paddingOuter` to 0px:

![3](https://user-images.githubusercontent.com/10929390/54061742-10e87080-41b7-11e9-9928-3f3cd7f59db6.png)

IMO, the first screenshot looks the best.

In the meantime, is there a workaround, other than manually messing with svg translate on svg internals?

**Comment by mbostock** [comment]
Did you try [*band*.align](https://github.com/d3/d3-scale/blob/master/README.md#band_align)?

**Comment by melissachang** [comment]
[Online editor link](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgFY6AK1jcAdpAA04KOlZ5usRgC9k2KIXQATBUsj6DBxjOq7gkADbIAZnl0AGeVDWFdARgDsHpAATozU+G6B7NwE3Ki+AGwAvooQkADujAYsugDMABwAnHQFeaI5oj6i8QBMoilQsHgAng66kPDIdnbGqQboeJg4ANpKEKAQE1Ay6Kg6OJDSrEEdAPquPZNQFOh2rMiwuiObE+PHE5CO6B14K9u7c1COaDs69WdQ8NysMi44-vHuUZnSAWVCzIw4S52WDIN7AvDIAAev0ezwcfz8AI270g3H0AEc9ro8EE9kDJslyScqZMLldkDc7kT5hhWnDju0vj9fH4ACyA969Rhg5AQsBQmHszaQBHItqs5AY-nY4F49CEh4ksnvSnvU44y7XW47ZmohUqjmfb4o-4CwUg4Xg3QS2E086ylEXNGKsC2i3StUa507GFu3VnfXAw0M433eUvf20q3cjEAqW00FOyEh12CzxIz0KpXrdPnQOml1hqkAXSB4bGVMg01mbT6AzW-oWX2WDy7S1WJcbJPQMlgjm4QTiwzdkY5zUIvfHk9YdkwpdSSMIQVb-VYqCGAB06Uamcgj9WALxXo9PBVHsAAfjArjAODbe8Px5jp-PV4vR7vSBH19V8wGqRNznQA55iaFZo0ZE1kBWaQghuSwDCRSAq2OWsKSUat6gWUJpmhQ4gVsZte1gxpkG8QJT1yHx6zAWcphmXsUFCcIpUgVhCDbXt2BHAxYH0DoAAoDFidBLHEgByJo5IASjoBwrBYDxXDoXkfAKTSlLAAAqMBqIRbw63wwiMCCABraCwCOakOUo+NbIOHj517IJkHgFweMaFoHiGSAhO3AjG0cIJYhsEF+kGKA23QDtmI3GRPgwmw3V4-j+geVikyWFCYoY+ZCG4SwEW3FLpUcRgujIvMG0a919k9d99yPZM8HPMA-zAGQVzsMAAB9hrARhYAAOXQSbJN3DrOWtc8lIgjkSv6wa3QpdcTgWeAE3mT47AnBRHkYToxQdEUjESLawHCvNcTE5gmhihADqgNV4Be06LnOuxLvLHRqtpNRuDsPBGG8HBbA0agSLaOS5IAanaz8PXPSAQfORE3v21p5lxwJaoutouqxnbIERcCYb2j6qd+9bXGx1JXtp96CagV7if+y74NjIkWdwZAuJRWH8ao36hJkMUtWQW6dSpBWJmVh6Ggl+zHKa6UXMJztPLaOxLGQdBtx4qSMEsGLEp3dsSzO0nDq5FxquCEdqCC9wWKI+GdjaDIskQLG1dpGRGA6YlSVzaVtCiyPtRVuFWKbdi2m5ocmgXNppaMc3pKtmGspt+ZEo7Us-sdx56QQuNy5QsWnvlK2ecryBYP509kInNCZcw5XtsbIJ3byhYzLe4i-Zg5Cx8SV2zAsKwAEkZBkZBtxwLSdL0xt58sagAHlVDXiJGx2Yi3DrJPG11j5wZOjzM97CcF79vPLbkWni4SuKy4dgHW0dKKX69d47yx4kPKwQVIAAGJeT7XYAYXkv1oHsCeD4Rw6wQ7nAqmvMqq4ERtEQPAbol9yLX1TvML6P0H5Z1KuVbkb8ZIf29l-WKdtfok3-pQgkRJAggJwHLV2ECPaHC9j4XCKtLImHQIifYDUnLSg5r2ImjYJznRTFAKIMQ4g8WoCEMULoeKrnYJ0AAYrIPAABlLQDwfB2lpMYsxuxYBBwEVHIx6ATF2H3lQIIq5oZgDlh5cONkADCztx6+26IdEWdhxIBxYKQfkK1XaaHQphP4pDJjJyUW0FRHI1HIA0SFaIagdGNj0ZkSxEs06dkqbLdxQ4QnhOtJEhGMS6rxMyIk5JFNGwWyYcGaE0cHGeM6PZQxjYMCIgAKLIiKSiex5xUCWDmQiDRSzUiQ3gHZIZkpGxpN7rjDeWSFG0lyTBTshTikOGcHU-ReyRnnEcXYcxPxrHaF8NUDxXiAAywpmBfM2VAQ5GFjm+gshANWnIZC1WsIXWkMiJqZQ5C88Jx115QGgTkHFjhRDgR+WYixbQACyFiYRBCHn5RsLy3l4AAOoizCCiUQrhgX2DGXYAACoYBe8KwDbznCEiZOZIVgFuokIAA/view)

I couldn't figure out `align`. I tried putting different numbers for `align`, but nothing changed.
<pre>
    {
      "name": "y",
      "type": "band",
      "domain": {
        "data": "data_0",
        "field": "facet_value",
        "sort": {"op": "min", "field": "y_facet_value_sort_index"}
      },
      "range": {"step": {"signal": "y_step"}},
      "paddingInner": 0.419,
      "paddingOuter": 0,
<b>      "align": 0 </b>
    },
</pre>

**Comment by mbostock** [comment]
Are you looking for help with Vega? This is D3.

**Comment by melissachang** [comment]
I am using vega-lite. I would like a `paddingOuterTop`/`paddingOuterBottom` for vega-lite. I figure it needs to be in D3 first.

When you suggested trying `band.align`, what did you have in mind? I assumed it would be possible to fiddle with `align` in vega online editor.

**Comment by curran** [comment]
How would `paddingOuterTop` be different than adjusting the top margin?

I wonder if the issues could be addressed by margin adjustment, instead of introducing a new feature in d30scale.

**Comment by mbostock** [comment]
Here, I wrote this explainer for you:

https://observablehq.com/@d3/band-align

I can’t answer your Vega questions. You’ll want to ask in a Vega-appropriate forum for help.

**Comment by melissachang** [comment]
Thanks. I had missed that *align* only applies to *outerPadding*. (The documentation is quite good, I should have read it more carefully.) That's why my vega editor link didn't work; *outerPadding* was 0.

**Comment by melissachang** [comment]
Oh, I see you just updated the documention to explicity mention outer padding. I don't feel as bad. :)

**Comment by mbostock** [comment]
Technically it’s not just outer padding because you can also get unused space if you use *band*.round to round to exact pixels, so the previous documentation was more accurate but less obvious.
