### ISSUE TITLE
d3.scaleSequentialQuantile doesn't clamp

### ISSUE THREAD

**Issue by Fil** [d3/d3-scale#172]
Instead it returns -1/(n-1) for values inferior to the min, and 1 for values superior to the max (because it uses bisect = bisectLeft).

In my understanding it would make no sense to have clamp(false), so maybe it's not worth exposing a clamp method, but returning -1/(n-1) instead of 0 seems like a (small) bug, and seems inconsistent with d3.scaleQuantile.

https://github.com/d3/d3-scale/blob/master/src/sequentialQuantile.js#L10

add Math.max(0,…) ?

**Comment by mbostock** [comment]
Or `bisect(domain, x, 1)`?
