### ISSUE TITLE
sequential.range(range) should set the interpolator to d3.interpolate.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-scale#188]
I mean, why not? Also, scale.rangRound could work the same way. And diverging.range could function similarly.

**Comment by Fil** [comment]
I wonder if there's not a missed opportunity here:

"sequential.range(range) ignores additional values"
https://github.com/d3/d3-scale/blob/60858c6adcdd7f88acda1c58c81b2a9cf11bc84f/test/sequential-test.js#L121

wouldn't it be nice to have `d3.scaleSequential(["blue", "green", "yellow"])` return a piecewise interpolator between these 3 values?
