### ISSUE TITLE
Are `null` and `undefined` valid inputs to `scale` / `domain` ?

### ISSUE THREAD

**Issue by RyanCavanaugh** [d3/d3-scale#193]
Context: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38314

We're unsure if the categorical `.scale` and `.domain` methods should be defined to accept `null` and `undefined`, e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38314#issuecomment-533307715

What is the authors' opinion?

**Comment by mbostock** [comment]
An ordinal scale “accepts” null and undefined (as in it does not throw an error), but these values are implicitly coerced to strings before use, and so are considered equivalent to `"null"` and `"undefined"` respectively.

https://observablehq.com/d/8aa6d6a50ca27793

In a type-safe context, I would not consider the scale function or the scale.domain method as accepting null or undefined; only string and array of string respectively.
