### ISSUE TITLE
Awkward wording issue in sequential scales documentation

### ISSUE THREAD

**Issue by curran** [d3/d3-scale#194]
As I was reading through the documentation for [sequential scales](https://github.com/d3/d3-scale#sequential-scales), I came across the following sentence, which I find a bit confusing:

>However, unlike continuous scales, the input domain and output range of a sequential scale always has exactly two elements, and the output range is typically specified as an interpolator rather than an array of values.

This sentence contains the statement

>  the ... output range of a sequential scale always has exactly two elements

Is this really true?

This statement seems to contradict the statement

> the output range is typically specified as an interpolator rather than an array of values

It may be appropriate to delete the text "and output range" from that statement.

What do you think? Thanks!

**Comment by Fil** [comment]
As noted by @clhenrick, _sequential_.range and _sequential_.rangeRound were introduced in [d3-scale 3.1.0](https://github.com/d3/d3-scale/releases/tag/v3.1.0), at https://github.com/d3/d3-scale/commit/60858c6adcdd7f88acda1c58c81b2a9cf11bc84f

I'm a bit lost too on how to use this; testing seems to show that _sequential_.range is only a getter, in contradiction with the documentation (??).

**Comment by mbostock** [comment]
The generated code is somehow `"function(){return[a(0),a(1)]}"` so I expect there’s a Terser bug at play here.

**Comment by mbostock** [comment]
No, it looks like *sequential*.range hasn’t been released yet.

**Comment by mbostock** [comment]
Er, *sequential*.range was added as a read-only method in 3.1, and changed to allow setting the interpolator in 3.2. So everything is as it should be, except master was ahead of the latest release, because I am only human.
