### ISSUE TITLE
Scale Band question

### ISSUE THREAD

**Issue by Tatamethues** [d3/d3-scale#196]
[example](https://observablehq.com/@tatamethues/untitled)
Hi, Please look at the example. I found that when the domain has many values, the padding outer becomes large. Is this a bug?

![GLISL)50M8{ EK)A{F`H3PI](https://user-images.githubusercontent.com/34636866/67768422-72828580-fa8d-11e9-94b0-3aa61452e57d.png)

![}Y@ S UB9PR~O20`0R5A{ 2](https://user-images.githubusercontent.com/34636866/67768465-84fcbf00-fa8d-11e9-8e45-61793d768a82.png)

based on the calculation, I think 1 should print 3, 2 should print 6，but the result was 141 and 144

**Comment by mbostock** [comment]
This is the expected behavior when you have pixel-snapping enabled using *scale*.round.
