### ISSUE TITLE
Wrong Continuous Scale range value for very small negative domain values

### ISSUE THREAD

**Issue by shahriar-newaz-modelon** [d3/d3-scale#199]
This small example should be enough to reproduce the issue.
This range seems not valid in the following cases where the start value for y is a small number like `-4.432589397526337e-8`.  Shouldn't the value be withing the range ?
```
    const x = d3.scaleLinear()
      .domain([0, 10])
      .rangeRound([0, 300]);

   const y = d3.scaleLinear()
      .domain([-4.432589397526337e-8, 0])
      .rangeRound([230, 0]);

y(0.0000875051170287688)  // gives us -452076 which is way bigger than the range

```

**Comment by Fil** [comment]
It looks correct to me — 0.0000875 is outside the domain of *y* (which is spanning only negative numbers).

**Comment by mbostock** [comment]
You can use scale.clamp if you want to constrain the output value to the range.
