### ISSUE TITLE
Time scales can fail on fractional timestamp values.

### ISSUE THREAD

**Issue by jheer** [d3/d3-scale#200]
We've run into cases involving zooming or axis padding where one needs a time/utc scale domain with end points that have fractional timestamp values. However, the current scale implementation appears to forcibly coerce numeric inputs to Date values, which then distorts the intended scale domain. Might it be possible to update the time and utc scales to respect input domain values provided as numeric timestamps, including those with fractional components?

**Comment by mbostock** [comment]
I don’t think this will be possible. Time scales’ domains are Date objects by definition, and Date objects only have millisecond precision in JavaScript. I think you’ll need to switch to a linear scale if you want to represent dates with greater precision.
