### ISSUE TITLE
IE Error: Const must be initialized

### ISSUE THREAD

**Issue by brookallen** [d3/d3-scale#201]
At line 31002:
  scale.domain = function(_) {
    if (!arguments.length) return domain.slice();
    domain = [], index = new Map();
    **for (const value of _) {**
      const key = value + "";
      if (index.has(key)) continue;
      index.set(key, domain.push(value));
    }
    return scale;
  };

_For IE 11 this errors out and will not render..._

**Comment by Fil** [comment]
IE11 does not support ES6, see the notes at https://github.com/d3/d3-scale/releases/tag/v3.0.0 for solutions.
