### ISSUE TITLE
scaleQuantize.range throws an error if the range is empty?

### ISSUE THREAD

**Issue by nickofthyme** [d3/d3-scale#203]
The code below is invalid per [spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length)

https://github.com/d3/d3-scale/blob/732ed4b1cd5c643700571d1089c7deb8472242a6/src/quantize.js#L18-L19

Running...
```js
new Array(-1);
```

Results in the following error
```bash
Uncaught RangeError: Invalid array length
    at <anonymous>:1:1
```

**Comment by mbostock** [comment]
It looks like you specified an empty range (so *n* = 1) and then called invertExtent. Did you intend to specify an empty range?

**Comment by nickofthyme** [comment]
@mbostock Thanks for clarifying so promptly.

I came across this with an empty dataset. I can see benefits for both options. For now, I can just pass a default range to avoid the error.

Thanks!
