### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property

### ISSUE THREAD

**Issue by Zicrael** [d3/d3-scale#205]
Uncaught TypeError: Cannot assign to read only property 'copy' of function 'function scale(x)
How I can fix it? I use
`import { scaleLinear } from "d3-scale"`

in part of inside lib code:

```
  var scale = continuous();

  scale.copy = function() { // <== error here
    return copy(scale, linear());
  };

  initRange.apply(scale, arguments);

  return linearish(scale);

```
P.S. Using Vue 2.4

**Comment by mbostock** [comment]
Sorry, but I have no idea what’s going wrong here. It would appear that your bundler is breaking the code somehow.
