### ISSUE TITLE
radial scale output

### ISSUE THREAD

**Issue by chethankambi** [d3/d3-scale#231]
// with ver 6.2.0
let radialScale = d3.scaleRadial();
radialScale(3);
Should the output be 9 or 1.73? Based on the API explanation, it should be 9 but the output is 1.73.
Am I missing something here?

**Comment by Fil** [comment]
the API doc says:
> an input value corresponds linearly to the squared output value.

input [0…3] does correspond linearly to the square of the output (which is [0…sqrt(3)]).

Maybe there is a way to make that sentence clearer?
