### ISSUE TITLE
Usage latest version (4.0.0) with react native 

### ISSUE THREAD

**Issue by Systerr** [d3/d3-scale#248]
Hi. I have a project build with react native that uses d3-scale. Before version 4 all works good. With version 4 i receiving error 

```
warn Package d3-scale has been ignored because it contains invalid configuration. 
Reason: Package subpath './package.json' is not defined by "exports"
```

On codebase it used as 
```javascript 
import { scaleLinear } from 'd3-scale'
```

**Comment by wilbo** [comment]
I got the same issue with version `3.0.1` from d3-array. Any clue?

**Comment by mbostock** [comment]
https://github.com/facebook/react-native/issues/28710
https://github.com/react-native-community/cli/issues/1168

**Comment by avneesh74** [comment]
> Hi. I have a project build with react native that uses d3-scale. Before version 4 all works good. With version 4 i receiving error
> 
> ```
> warn Package d3-scale has been ignored because it contains invalid configuration. 
> Reason: Package subpath './package.json' is not defined by "exports"
> ```
> 
> On codebase it used as
> 
> ```js
> import { scaleLinear } from 'd3-scale'
> ```

Did you find any solution for this, I am also facing this issue

**Comment by KieQuang** [comment]
+1 any help ! Please.

**Comment by aymather** [comment]
+1 please.. anybody with an answer... please..... *dies slowly*

**Comment by Fil** [comment]
As Mike mentioned above, this is a React Native tooling bug: https://github.com/react-native-community/cli/issues/1168
We don't intend to work around it.
