### ISSUE TITLE
ScaleTime ticks reset at the beginning of the month

### ISSUE THREAD

**Issue by tiagosilva1994** [d3/d3-scale#261]
Hey,

I'm trying to create a timescale for an x axis for a chart, I'm using timescale and the ticks are for every 2 days as in the code below.

```
xScale = d3.scaleTime()
                 .domain([startDate, endDate])
                 .rangeRound([0, width]);
axisBottom = d3.axisBottom(xScale).ticks(d3.timeDay.every(2));

g.append('g').call(axisBottom);
```

But the scale resets the count when a new month begins

Does anyone have a solution for this problem?
![Untitled](https://user-images.githubusercontent.com/102976947/161571216-e90db433-fc40-478e-a1a5-f86ab69f4ea7.png)

Thank you in advance,
Tiago

**Comment by mbostock** [comment]
Described here: https://github.com/d3/d3-time/blob/main/README.md#interval_every

> Note that for some intervals, the resulting dates may not be uniformly-spaced; [d3.timeDay](https://github.com/d3/d3-time/blob/main/README.md#timeDay)’s parent interval is [d3.timeMonth](https://github.com/d3/d3-time/blob/main/README.md#timeMonth), and thus the interval number resets at the start of each month.

I think you can use interval.filter instead of interval every if you want this behavior. If you want help, please try a help forum. Good luck.
