### ISSUE TITLE
d3.scaleTime() axis ticks are not aligned with scale outputs?

### ISSUE THREAD

**Issue by xiaohk** [d3/d3-scale#263]
Hello, I am using `d3.scaleTime()` and `d3.axisBottom()` to draw an x axis. However, in my case, the axis ticks are not aligned with the scale's outputs (blue dots).

<img width="623" alt="image" src="https://user-images.githubusercontent.com/15007159/175427683-994dbef6-377f-4c83-b6a4-14230d9737b1.png">

The example is in this [observable notebook](https://observablehq.com/@xiaohk/time-scale-x-scale-misalignment). Any suggestions are appreciated! Thanks!

**Comment by mbostock** [comment]
Try d3.scaleUtc (UTC time) instead of d3.scaleTime (your browser’s local time).

**Comment by xiaohk** [comment]
> Try d3.scaleUtc (UTC time) instead of d3.scaleTime (your browser’s local time).

It worked, thank you!
