### ISSUE TITLE
Possible Bug in log implementation

### ISSUE THREAD

**Issue by FelixBenning** [d3/d3-scale#271]
I am looking at https://github.com/d3/d3-scale/blob/main/src/log.js#L51-L60, i.e.

```javascript
  function rescale() {
    logs = logp(base), pows = powp(base);
    if (domain()[0] < 0) {
      logs = reflect(logs), pows = reflect(pows);
      transform(transformLogn, transformExpn);
    } else {
      transform(transformLog, transformExp);
    }
    return scale;
  }
```

The return value of `transform(transformLogn, transformExpn)` seems to be completely ignored, and instead `scale` is returned regardless. `scale` itself is defined in https://github.com/d3/d3-scale/blob/main/src/log.js#L45 as

```javascript
const scale = transform(transformLog, transformExp);
```

The `reflect` function looks a bit like a workaround to this bug, i.e. it makes the `transformLogn` and `transformExpn` functions superfluous. That being said: it seems a bit weird that the entire rescale function should be flipped if just the lower bound of the domain is smaller zero. What if the upper bound is greater zero?

I stumbled over this while trying to implement a tan-transform by looking at the log-transform. I haven't tested this, this might be complete bullshit

**Comment by mbostock** [comment]
Calling transform(…) mutates the behavior of the scale; the return value is irrelevant. See https://github.com/d3/d3-scale/blob/83555bd759c7314420bd4240642beda5e258db9e/src/continuous.js#L117-L120.

If you think you’ve found a bug, please send us a test case or example code that demonstrates the unexpected or perceived incorrect behavior, along with an explanation of what you expected.
