### ISSUE TITLE
Microseconds are not supported?

### ISSUE THREAD

**Issue by manake** [d3/d3-scale#272]
I have a fully working linear scale where each integer is supposed to be a millisecond:

```
let x = d3.scaleLinear().domain([left, right]).range([0, width]);
```

https://user-images.githubusercontent.com/6874031/211384150-5094e0ef-b1a1-4f67-8113-9a9cf0bf34c4.mp4

I switch this to a time scale and the x axis stops working (I assume because microseconds are not supported in d3.js and it modifies the domain to snap it to the nearest millisecond):
```
let x = d3.scaleUtc().domain([left, right]).range([0, width]);
```

https://user-images.githubusercontent.com/6874031/211384184-647d7fca-c5a3-47d1-a6f7-f64fc8e264e8.mp4

How can I fix this?

**Comment by mbostock** [comment]
JavaScript Date objects only have millisecond resolution so you’ll have to use a linear scale instead if you want microseconds.

**Comment by manake** [comment]
Thank you, I will try adding a custom display formatter.

But I also think it's an inconsistency because `scaleLinear()` is linearly interpolated and `scaleUtc()` could be too in such case.

Currently it seems to modify the domain and with linear interpolation it wouldn't, which would be better.

There are some rumors that a `Temporal` replacement for `Date` could appear, can't wait:
- https://caniuse.com/?search=temporal
- https://github.com/tc39/proposal-temporal
