### ISSUE TITLE
Update d3-interpolate dependency to v3

### ISSUE THREAD

**Issue by fresheneesz** [d3/d3-scale#277]
d3-interpolate depends on de-color v2, which has a high CEV vulnerability according to `npm audit`. Updating would solve this.

**Comment by mbostock** [comment]
It depends on 1.2.0 – 3, so you can upgrade.

https://github.com/d3/d3-scale/blob/83555bd759c7314420bd4240642beda5e258db9e/package.json#L38

**Comment by fresheneesz** [comment]
On second look, I can't update. I need to update to d3-interpolate v3, however `"d3-interpolate": "1.2.0 - 3",` does not allow this. That semvar means only versions below 3 (and  1.2.0 or above) are supported. Please reopen

**Comment by mbostock** [comment]
That’s not how semver ranges work, @fresheneesz. The upper bound of the range is inclusive.

**Comment by fresheneesz** [comment]
@mbostock [This cheatsheet](https://devhints.io/semver) as well as [node-semvar](https://github.com/npm/node-semver) say otherwise. Also pnpm refuses to update these dependencies. I don't think I'm wrong here.

**Comment by mbostock** [comment]
From the link you posted:

<img width="582" alt="Screenshot 2023-05-24 at 1 29 11 PM" src="https://github.com/d3/d3-scale/assets/230541/6ed07e77-191d-4797-86af-87537b4d8c6f">

In other words, `1.2.3 - 2` means all 2.x.y, but less than 3.0.0.
