### ISSUE TITLE
scaleTime() ticks issue

### ISSUE THREAD

**Issue by n9** [d3/d3-scale#285]
There is an issue with `scaleTime()`.

![image](https://github.com/d3/d3-scale/assets/1651867/8bed443c-855c-4641-b2f0-89a28e27c07b)

 It may be caused by summer to standard time transition as `scaleUtc()` is not affected.

![image](https://github.com/d3/d3-scale/assets/1651867/b7f6641a-0a3e-47dc-895e-731e068df4c7)

https://observablehq.com/d/0fc00a92609c21b0

**Comment by mbostock** [comment]
This is the intended behavior, but we are proposing a change here: https://github.com/d3/d3-time/pull/66

**Comment by n9** [comment]
What is a workaround for that? (From the UX perspective, it looks like a bug.)
