### ISSUE TITLE
log scale returns unwanted ticks

### ISSUE THREAD

**Issue by boygirl** [d3/d3-scale#33]
Hi there, I just made the switch from d3 to d3 modules, and I'm seeing some unexpected behavior with the log scale ticks. 

expected behavior:
domain = [1, 5]  tickCount = 5 ->  ticks = [1, 2, 3, 4, 5] 

actual behavior:
domain = [1, 5]  tickCount = 5 -> ticks = [1, 2, 3, 4, 5, 6, 7, 8, 9]

I looked through the source code briefly, and I think this line _might_ have something to do with the bug I'm seeing
https://github.com/d3/d3-scale/blob/master/src/log.js#L85

Thanks!

**Comment by mbostock** [comment]
Thanks for report. This is a new bug; I will investigate.

**Comment by boygirl** [comment]
@mbostock thanks for such a fast fix!
