### ISSUE TITLE
Probable bug

### ISSUE THREAD

**Issue by yuchi** [d3/d3-scale#43]
At [this line](https://github.com/d3/d3-scale/blob/25a7248265f5ff1623fc87a9e1268664d649b2f2/src/sequential.js#L22) the variable `sequential` is used but never defined.

You should probably change the definition of the function as follows:

```js
export default function sequential(interpolate) {
  //                    ^^^^^^^^^^
}
```

I actually didn’t tested nor experienced the bug so please feel free to close this issue if you think is silly!

Cheers

**Comment by mbostock** [comment]
Looks right. Thanks for the catch!

**Comment by yuchi** [comment]
That whole line comes from when functions where declarations and not properties.

Glad to help!

**Comment by yuchi** [comment]
There's also `domain` that doesn't look right to me :)

**Comment by mbostock** [comment]
Looks like this method escaped testing; I was planning on adding tests as
part of this fix and will catch whatever else is busted.
