### ISSUE TITLE
IP Addresses (and bignums)

### ISSUE THREAD

**Issue by syntagmatic** [d3/d3-scale#51]
An IP address scale would be nice to include in an extended scales plugin, but this repo seems like a good place to consider how to handle them.

For IPv4, there's a straightforward conversion to/from integers. These integers can then be put on a linear scale. See: http://bl.ocks.org/syntagmatic/1ced118a51b49dadd4ea

<img width="420" alt="screen shot 2016-02-02 at 2 27 37 pm" src="https://cloud.githubusercontent.com/assets/156229/12766516/245248b8-c9b9-11e5-8866-9925fd181328.png">

A better solution might be to use a library that converts IP addresses to objects, does data validation, etc. Then d3.scaleIPv4 could behave like d3.scaleTime.

Here's one such library: https://github.com/beaugunderson/ip-address

But since IPv6 addresses are 128 bits, they can't be represented by integers. The ip-address library uses a BigInteger format to resolve this. But it's not obvious to me how I would construct a d3 scale with BigIntegers.

A related problem is representing bignums in general, say those produced by https://github.com/MikeMcl/bignumber.js/

**Comment by mbostock** [comment]
I don’t have any immediate plans to implement this, and it feels more appropriate as a plugin (as you suggest), so I’m going to close this issue.

It does make me think of this XKCD, though…

[![map_of_the_internet](https://cloud.githubusercontent.com/assets/230541/12769293/873e550e-c9cb-11e5-905e-0b0a8d00b25b.jpg)](https://xkcd.com/195/)

**Comment by syntagmatic** [comment]
I'll toss the idea of d3.scaleBignum into the wind and see if anyone runs with it.
