### ISSUE TITLE
Broken Link for #Linear in README.md

### ISSUE THREAD

**Issue by kanitw** [d3/d3-scale#52]
There are links pointing to `#linear` section throughout `README.md`.
However, the linear scale is explained as a part of `#continuous-scales` section without its own separate section.  Thus all the `#linear` links are broken.

**Comment by mbostock** [comment]
I think I’ve fixed ’em, but if you find any more, please fix and send me a pull request? Thanks.

**Comment by kanitw** [comment]
Ok :)
