### ISSUE TITLE
Simplify the naming?

### ISSUE THREAD

**Issue by chrisprice** [d3/d3-scale#53]
To create a linear scale I run something like -

```js
const x = d3_scale.scaleLinear()
```

However, I had assumed I would instead do -

```js
const x = d3_scale.linear()
```

It's my first time playing with the new modules and I know it's easy to go blind to these things, so thought I'd raise the issue. It's obviously not a big deal but thought it might be useful feedback.

**Comment by mbostock** [comment]
I’m aware of this issue, but I’m not sure how to make things any clearer. See mbostock/d3#2749 for one idea which I have rejected, and d3/d3-queue#56 for a similar issue.
