### ISSUE TITLE
include standalone version in build folder

### ISSUE THREAD

**Issue by wilzbach** [d3/d3-scale#58]
It's great to see that d3 is so modular nowadays, but for some of us using a standalone bundle is often the best choice.
It would be very convenient if a standalone bundle would be part of the npm package. Maybe you can just put it to the build folder too?

**Comment by wilzbach** [comment]
i figured out that this is probably a lot of work for every bundle and not worth the benefit. please ignore and sorry about the noise.

**Comment by mbostock** [comment]
Exactly. There is a self-contained bundle of D3 4.0, however: see the [D3 README](https://github.com/mbostock/d3/blob/4/README.md) or `npm install d3@next` to get it.
