### ISSUE TITLE
Don’t assume ordinal / sequential?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-scale#63]
From d3/d3-scale-chromatic#2:

* I might want to use a categorical color scheme with a different type of scale, such as a [threshold scale](https://github.com/d3/d3-scale#threshold-scales). (Somewhat unlikely, though, as thresholds are typically ordinal.) Or I might want to use a categorical color scheme for some other purpose; it’s not clear we should strictly assume d3.scaleOrdinal, although it is trivial to extract the range from an ordinal scale.

* I might want to use a diverging or sequential color scheme with a different type of scale, say if there is a log- or pow-transformed sequential scale in the future (#61). I might also just want direct access to the scale’s underlying interpolator for some reason.

**Comment by mbostock** [comment]
One option would be to expose interpolators:

* d3.interpolateViridis
* d3.interpolateInferno
* d3.interpolateMagma
* d3.interpolatePlasma
* d3.interpolateWarm
* d3.interpolateCool
* d3.interpolateRainbow
* d3.interpolateCubehelixDefault (or interpolateGreen? interpolateCubehelixGreen?)

Then if you want to create a sequential scale, you use d3.scaleSequential. So this:

```js
var color = d3.scaleRainbow();
```

Is replaced with this:

```js
var color = d3.scaleSequential(d3.interpolateRainbow);
```

Which isn’t too bad, and perhaps makes the interface more obvious, and affords a simple way of replacing the type of sequential scale (#61):

```js
var color = d3.scaleSequentialLog(d3.interpolateRainbow);
```

Similarly for the category color schemes, we could have methods that return arrays of strings:

* d3.schemeCategory10
* d3.schemeCategory20
* d3.schemeCategory20b
* d3.schemeCategory20c

Then to create an ordinal scale, instead of this:

```js
var color = d3.scaleCategory10();
```

You’d say this:

```js
var color = d3.scaleOrdinal().range(d3.schemeCategory10());
```

Perhaps we could also change the d3.scaleOrdinal constructor to take the output range as input, since an ordinal scale is useless until the range is specified. Then you could say:

```js
var color = d3.scaleOrdinal(d3.schemeCategory10());
```

We could also just make the scheme an array of colors rather than a method, and why not, since it’s always the same:

```js
var color = d3.scaleOrdinal(d3.schemeCategory10);
```

**Comment by curran** [comment]
I like the idea of decoupling the scale from the range (scheme) that it provides.
