### ISSUE TITLE
d3.interpolateCubehelixDefault doesn't match documentation

### ISSUE THREAD

**Issue by pbeshai** [d3/d3-scale#68]
The docs suggest that you can pass it a `t` value directly and get back a color (from README):

> #### d3.interpolateCubehelixDefault(t)
> Given a number t in the range [0,1], returns the corresponding color from Green’s default Cubehelix represented as an RGB string.

Instead it returns a function that when called produces the desired behaviour:
![image](https://cloud.githubusercontent.com/assets/793847/16093099/84d295e0-3308-11e6-9ec1-48b090507834.png)

The other interpolateFoo functions work as expected. 

Using d3-scale 0.9.1.

**Comment by mbostock** [comment]
Oops! Thanks for the report. Fixed in 0.9.2.

**Comment by curran** [comment]
Woot!

[![image](https://cloud.githubusercontent.com/assets/68416/16244273/d9f8fd92-3818-11e6-91c4-c2893e30d50e.png)](http://bl.ocks.org/curran/raw/3094b37e63b918bab0a06787e161607b/#CubehelixDefault)
