### ISSUE TITLE
Cannot chain scaleTime functions when using in Node environment.

### ISSUE THREAD

**Issue by tshrestha** [d3/d3-scale#73]
From the [timeScale](https://github.com/d3/d3-scale/blob/master/README.md#time-scales) documentation it looks like you should be able to chain the `domain()` and `range()` calls, but when using it in a Node environment, you can only call one or the other.

When chaining the `domain()` and `range()` calls the following error is thrown:

```
TypeError: scale.scaleTime(...).domain(...).range is not a function
```

The code snippet I'm working with:

```javascript
const scale = require('d3-scale');

// The following code throws the error
// TypeError: scale.scaleTime(...).domain(...).range is not a function
let x = scale.scaleTime().domain().range();

// But the following code works
let x = scale.scaleTime();
x.domain();
x.range();
```

I assume this isn't intended? Or am I missing something here?

**Comment by mbostock** [comment]
If you call scale.domain with no arguments, it returns the current domain. If you call it with arguments it sets the domain and returns the scale to allow chaining. This is the standard behavior of D3’s getter-setter methods. See a chaining example here:

https://tonicdev.com/5775df609f199c13001afdd5/578fe02c34681f1300fe0c09

**Comment by mbostock** [comment]
(That example has a domain with only one value which is a mistake… since I am replying on my phone, sorry.)
