### ISSUE TITLE
linear.nice should use d3.tickIncrement for precise rounding.

### ISSUE THREAD

**Issue by pavlin99th** [d3/d3-scale#81]
Say you want a nice linear scale and ticks for your `[5.83, 6.2]` domain.
Due to float calculations .nice() sets the domain to:

> d3.scaleLinear().domain([5.83, 6.2]).nice().domain()
> [5.800000000000001, 6.2]

and .ticks() returns:

> d3.scaleLinear().domain([5.83, 6.2]).nice().ticks()
> [5.8500000000000005, 5.9, 5.95, 6.000000000000001, 6.050000000000001, 6.1000000000000005, 6.15, 6.2]

Now you are missing the first 5.8 tick.

I know this happens because of float calculations (`0.05 * 116`), what is the best way to deal with the situation? Should it be solved by d3 or by a user?

I ended up with rounding and resetting the domain with the help of d3.format, but looking for a more general solution.

**Comment by mbostock** [comment]
Thanks for the report. I think we can fix this without too much trouble. This will affect both d3-array and d3-scale, since the core tick methods are in d3-array, but the implementation of *linear*.nice will be affected. Rather than tracking this in both places, let’s just use d3/d3-array#45.

**Comment by pmalouin** [comment]
Just a heads up that I can still reproduce this issue with the latest version of d3-array (1.2.0). I expected https://github.com/d3/d3-array/commit/04cf783bd715cae89303173d50a28fda38c24a9b would solve the problem.

Here are my dependencies:
```
└─┬ d3-scale@1.0.5
  ├── d3-array@1.2.0
  ├── d3-collection@1.0.3
  ├── d3-color@1.0.3
  ├── d3-format@1.2.0
  ├── d3-interpolate@1.1.4
  ├── d3-time@1.0.6
  └── d3-time-format@2.0.5
```
```
> var d3Scale = require('d3-scale');
undefined
> d3Scale.scaleLinear().domain([5.83, 6.2]).nice().domain()
[ 5.800000000000001, 6.2 ]
> d3Scale.scaleLinear().domain([5.83, 6.2]).nice().ticks()
[ 5.85, 5.9, 5.95, 6, 6.05, 6.1, 6.15, 6.2 ]
```

**Comment by mbostock** [comment]
No; linear scales still use [d3.tickStep](https://github.com/d3/d3-array/blob/master/README.md#tickStep), not the new [d3.tickIncrement](https://github.com/d3/d3-array/blob/master/README.md#tickIncrement), and so there’s no protection against rounding errors. See [linear.js](https://github.com/d3/d3-scale/blob/v1.0.5/src/linear.js#L18-L34).

However, I don’t see any reason why we couldn’t update *linear*.nice to use d3.tickIncrement and thus guarantee exact behavior (within the limits of IEEE 754). So I’ll reopen and retitle this issue accordingly.
