### ISSUE TITLE
Possible Readme typo

### ISSUE THREAD

**Issue by ryunp** [d3/d3-scale#82]
Seems to be a typo under the [scalePoint](https://github.com/d3/d3-scale#point_range) section.

The domain method states:
> \# point.domain([domain])
> If domain is specified, sets the domain to the specified array of values. 

While just below that the range method references a domain variable:
> \# point.range([range])
> If **domain** is specified, sets the scale’s **domain** to the specified two-element array of numbers...

**Comment by curran** [comment]
Good catch! I have made a PR to address this https://github.com/d3/d3-scale/pull/84
